### ISSUE TITLE
Automatically download language server binaries

### ISSUE THREAD

**Issue by slrtbtfs** [nevill/LSP-promql#1]
First, thanks for this project.

It would be nice if the Plugin could automatically download the latest language server binary from the GitHub releases page instead of requiring manual compilation and updating.

**Comment by nevill** [comment]
Now, with the newly released version 0.1.2, it downloads `promql-langserver` 0.5.1 automatically, available via Package Control. :)

**Comment by slrtbtfs** [comment]
Cool! So there will be an extension update every time there is a language server update?

**Comment by nevill** [comment]
> Cool! So there will be an extension update every time there is a language server update?

Yes, if we need. Unfortunately it's not an automatic process.

**Comment by nevill** [comment]
As you may see [here](https://github.com/nevill/LSP-promql/blob/master/plugin.py#L14-L33).

**Comment by slrtbtfs** [comment]
The VS Code extension handles things the same way. So I guess that's ok for now.
